chore: automatically record screenshots for PRs on failure
closes #788

reference: https://github.com/android/nowinandroid/blob/dac1a9e446dd8bd41012227ba59bb65ffba7adad/.github/workflows/Build.yaml#L75-L100

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -19,17 +19,46 @@ jobs:
         uses: ./.github/actions/setup
 
       - name: Detekt non-KMP code smells
+        continue-on-error: true
         run: ./gradlew detekt
 
       # https://github.com/detekt/detekt/issues/3665
       - name: Detekt KMP code smells
+        continue-on-error: true
         run: ./gradlew detektMetadataMain
 
       - name: Unit test all kotlin modules
+        continue-on-error: true
         run: ./gradlew testKotlinModules
 
       - name: Unit test all KMP modules
+        continue-on-error: true
         run: ./gradlew testKotlinMultiplatformModules
 
       - name: Verify screenshot tests
+        id: screenshotsverify
+        continue-on-error: true
         run: ./gradlew verifyPaparazziDebug
+
+      - name: Prevent pushing new screenshots if this is a fork
+        id: checkfork_screenshots
+        continue-on-error: false
+        if: steps.screenshotsverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Screenshot tests failed, please create a PR in your fork first." && exit 1
+
+      # Runs if previous job failed
+      - name: Generate new screenshots if verification failed and it's a PR
+        id: screenshotsrecord
+        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
+        run: |
+          ./gradlew recordPaparazziDebug
+
+      - name: Push new screenshots if available
+        uses: stefanzweifel/git-auto-commit-action@v5.0.0
+        if: steps.screenshotsrecord.outcome == 'success'
+        with:
+          file_pattern: '*/*.png'
+          disable_globbing: true
+          commit_message: "chore: updates screenshots"
+          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
